//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loners.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public string AboutMe { get; set; }
        public string MBTI { get; set; }
        public string Biorytmus { get; set; }
        public string InterestsHobbies { get; set; }
        public string Status { get; set; }
        public string DateOfRegistration { get; set; }
    }
}
